EO-DataHub/eodh-fe

- libs/shared/design-system/src/lib/slider/slider.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-260
> UKRIW-260 Slider component - different behavior in Safari and Chrome browsers

- libs/map/data-access-stac-catalog/src/lib/query-builder/filter-params/copernicus/sentinel-2.filter-params.ts
fix error when cloud coverage is 0 (request was send with <= 0 condition).
tasks:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-405
> fix: add support for 0 cloud coverage

- libs/shared/design-system/src/lib/result-item/result-item.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-358
Fixed bug: Once cloud coverage is 0, Cloud coverage metadata is displayed wrongly
> UKRIW-358 - cloud coverage bug fix

- libs/shared/design-system/src/lib/button/button.styles.tsx
- libs/shared/design-system/src/lib/button/button.tsx
- libs/shared/design-system/src/lib/button/use-safari-fix.hook.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-415
This pull request introduces several enhancements to the button component in the design system, focusing on adding an `isActive` state to handle active styling and improving the button's click and focus behavior especially on Safari browser.
> UKRIW-415 - fixed button active state for Safari browser

- apps/eodh-fe/public/assets/i18n/en.json
- libs/map/feature-action-creator-panel/src/lib/content/content.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/presets.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/presets/preset.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/presets/preset.stories.tsx
- libs/map/feature-action-creator-panel/src/lib/content/presets/preset.styles.ts
- libs/map/feature-action-creator-panel/src/lib/content/presets/presets.component.tsx
- libs/shared/theme/src/lib/dark-theme.config.ts
- libs/shared/theme/src/lib/ligh-theme.config.ts
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-437
> UKRIW-437 - basic Preset component

- package-lock.json
- package.json
Add workflow tab (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-80)
Fixed errors:
- Once cloud coverage is 0, Cloud coverage metadata is displayed wrongly (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-358)
- After clicking "View/Hide" button on a thumbnails, the button stays in the hover state (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-415)
> Bump version to 0.6.0 in package.json

- libs/map/feature-action-creator-panel/src/lib/content/history/history.component.tsx
Fix for **Load more** button to display it only when current page is not equal total pages
> UKRIW-410 - Load more button displaying fix

- libs/map/data-access-map/src/lib/action-creator-store/action-creator.model.ts
- libs/map/data-access-map/src/lib/action-creator-store/action-creator.store.tsx
- libs/map/data-access-map/src/lib/mode-store/toggle-state.ts
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/area-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/data-set/data-set-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/date-range/date-range-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/function-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/header/tabs.component.tsx
Fix not reseting state in Workflow while switching to AC and Search mode
tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-510
> fix: fix not reseting state workflow while switching to AC and Search mode

- libs/map/data-access-map/src/lib/mode-store/toggle-state.ts
Fix error which cause disabled Data Sets and missing Search button while switching back to Search Mode
ticket:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-518
> [UKRIW-518] reset state only for Action Creator mode

- libs/map/feature-action-creator-panel/src/lib/content/history/history-tile/history-tile.component.tsx
- libs/shared/utils/date/src/index.ts
- libs/shared/utils/date/src/lib/date.utils.ts
- libs/shared/utils/date/src/lib/time.utils.ts
updated displayed date and time to be local date/time not UTC date/time
> UKRIW-410 -  updated displayed date and time to be local date/time

- .github/workflows/pull-request.yml
- libs/map/data-access-map/src/index.ts
- libs/map/data-access-map/src/lib/mutation/get-intersects.ts
- libs/map/data-access-map/src/lib/query/presets.model.ts
- libs/map/data-access-map/src/lib/store/action-creator/action-creator.model.ts
- libs/map/data-access-map/src/lib/store/action-creator/action-creator.store.tsx
- libs/map/data-access-map/src/lib/store/action-creator/node.utils.ts
- libs/map/data-access-map/src/lib/store/data-sets/data-sets.model.ts
- libs/map/data-access-map/src/lib/store/data-sets/data-sets.store.tsx
- libs/map/data-access-map/src/lib/store/utils.ts
- libs/map/feature-action-creator-panel/src/lib/content/presets/preset.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/presets/presets.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/active-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/area-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/value-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/data-set/data-set-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/data-set/value-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/date-range/date-range-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/date-range/value-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/empty-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/active-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/function-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/loading-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/value-node.component.tsx
- libs/map/ui-search-view/src/lib/tree/copernicus/sentinel-2.component.tsx
Load Preset into Workflow
Ticket:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-471
> [UKRIW-367] load preset

- libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.store.tsx
- libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-modal/onboarding-modal.tsx
- libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
- package-lock.json
- package.json
- Designing workflow (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-90, https://ukri-spyrosoft.atlassian.net/browse/UKRIW-94, https://ukri-spyrosoft.atlassian.net/browse/UKRIW-359, https://ukri-spyrosoft.atlassian.net/browse/UKRIW-86)
- Viewing workflow history (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-410)
- Global Data Store (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-384)
- Run Single Workflow (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-113)
- Load Preset (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-367)
> Release v7.0.0

- libs/map/data-access-map/src/index.ts
- libs/map/data-access-map/src/lib/query/protected-image.query.tsx
- libs/map/ui-results-view/src/lib/results-list/result-item/result-item.tsx
- libs/shared/utils/react-query/src/index.ts
- libs/shared/utils/react-query/src/lib/axios.ts
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-120
> UKRIW-120 - display Thumbnail image

- package-lock.json
- package.json
- Display Workflow Results (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-120)
- Display selected Workflow Asset on the map (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-122)
- Display backend validation errors for running Workflow (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-442)
- Fix error: "The application does not remember the state after switching between search and AC modes" (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-546)
> Release v0.8.0

- libs/map/feature-search-mode-panel/src/lib/results-view.component.tsx
- libs/map/ui-results-view/src/lib/results-list/result-item/result-item.tsx
- libs/shared/utils/date/src/index.ts
- libs/shared/utils/date/src/lib/time.utils.ts
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-402
- fixed time format bug
- fixed some styling issues
> UKRIW-402 - fixed time format bug

- package-lock.json
- package.json
- fix wrong format time → HH:MM instead of HH:MM:SS 
- fix Displayed time is shifted +1h compared to the one returned by API
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-402
> Release v0.9.1

- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/value-node.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-564
> UKRIW-564 - bug fix for: Can run the workflow for an area larger than 1000 km2

- docs/release-process.md
Add rollback process.
Ticket:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-430
> [UKRIW-430] add rollback process to release documentation

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
- libs/map/data-access-map/src/lib/mutation/workflow.error.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/function-node.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-637
Bug fix
> UKRIW-637 - translation bug fix

- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/value-node.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-627
Resolved bug for map crashing after drawing circle AOI
> UKRIW-627 - resolved bug for map crashing after drawing circle aoi

- apps/eodh-fe/src/app/layout/left-menu.component.tsx
- libs/map/data-access-map/src/lib/store/toggle-mode.ts
- libs/map/feature-action-creator-panel/src/lib/content/history/history.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/presets/presets.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/workflow.component.tsx
- libs/map/ui-results-view/src/lib/results-list/result-item/result-item.tsx
- libs/shared/design-system/src/lib/button/button.styles.tsx
- libs/shared/design-system/src/lib/select/select.styles.tsx
- fixed button bug on ResultView: https://ukri-spyrosoft.atlassian.net/browse/UKRIW-462
- fixed scroll issues:
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-482
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-509
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-526
- fixed image overlay bug: https://ukri-spyrosoft.atlassian.net/browse/UKRIW-648
> UKRIW-648 - fixed button bug on ResultView(462); fixed scroll issues(482,509,526); fixed image overlay bug(648)

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
- libs/map/feature-action-creator-panel/src/lib/action-creator.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/container.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/history/history.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/modals/modal/modal.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/modals/modal/modal.styles.tsx
- libs/map/feature-action-creator-panel/src/lib/content/modals/unactive-ac-mode-modal/unactive-ac-mode-modal.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/modals/unlogged-user-modal/unlogged-user-modal.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/modals/workflow-processing-modal/workflow-processing-success-modal.component.tsx
- libs/map/ui-search-view/src/lib/dynamic-tree-form/elements/tree-category/use-control.hook.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-611
Added modals:
- If user is logged out and unfold ActionCreator -> `UnloggedUserModal`
- If user is logged in and in search mode and unfold ActionCreator -> `UnactiveAcModeModal`
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-512
Fixed bug "View results" and "Load more" buttons - padding right/left property
> UKRIW-611 - Action Creator modals

- libs/map/data-access-stac-catalog/src/index.ts
- libs/map/data-access-stac-catalog/src/lib/stac.model.ts
- libs/map/ui-results-view/src/lib/results-list/download-files.utils.ts
Fix not displaying water quality results.
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-612
> [UKRIW-612 ] fix not displayed water quality results

- libs/map/data-access-map/src/lib/query/function/function.query.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/workflow.component.tsx
- disable buttons in AC when AC is not enabled.
- not load supported data sets when AC is not enabled
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-668
> [UKRIW-668] disable buttons in AC when AC is not enabled

- libs/map/feature-action-creator-panel/src/lib/action-creator-panel.context.tsx
- libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
- libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.store.tsx
Start onboarding only when AC is enabled.
Ticketd:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-688
> [UKRIW-688] hide onboarding tooltip when AC not enabled

- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/value-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/workflow.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-564
Bug fix
> UKRIW-564 - bug fix - Can run the workflow for an area larger than 1000 km2

- libs/shared/design-system/src/lib/select/select.styles.tsx
Fix inner width in select (truncat text to container width)
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-710
> [UKRIW-710] truncate text to full container width

- libs/map/feature-timeline-analytics-dashboard/src/lib/graph-analytics.component.tsx
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-701
> [UKRIW-701] show no data error when there is no data in charts

- libs/map/feature-timeline-analytics-dashboard/src/lib/charts/range-area/range-area-with-line-one-series-chart.component.tsx
- libs/map/feature-timeline-analytics-dashboard/src/lib/charts/stack-bar/bar-chart.component.tsx
- libs/map/feature-timeline-analytics-dashboard/src/lib/charts/stack-bar/bar-chart.model.ts
Disable data labels on charts:
- stackbar
- stackbar 100%
- rangeArea
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-705
> [UKRIW-705] disable data labels in charts

- libs/map/data-access-map/src/lib/store/action-creator/workflow-import/import.workflow.ts
- libs/map/data-access-map/src/lib/store/utils.ts
Fix Workflow and Presets import when there are empty function nodes.
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-718
> [UKRIW-718] fix: fix workflow and preset import with empty functions

- libs/map/feature-action-creator-panel/src/lib/content/workflow/workflow.component.tsx
Remove padding in import/export buttons in AC
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-717
> [UKRIW-717] fix: adjust AC import and export buttons padding to met design

- libs/map/ui-map/src/lib/layers/measure-distance-layer/measure-distance-panel/use-distance.hook.tsx
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-729
> [UKRIW-729] fix: fix not displaying correct measure distance after toggle

- libs/map/data-access-map/src/lib/store/aoi/aoi.model.ts
- libs/map/data-access-map/src/lib/store/aoi/aoi.store.tsx
- libs/map/ui-map/src/lib/layers/aoi-layer/use-aoi-layer.hook.tsx
- libs/map/ui-map/src/lib/layers/measure-distance-layer/measure-distance-layer.hook.tsx
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-730
> [UKRIW-730] feat: disable drawing measure distance when drawing AOI is enabled

- libs/map/ui-map/src/lib/layers/measure-distance-layer/measure-distance-button.component.tsx
- libs/map/ui-map/src/lib/layers/measure-distance-layer/measure-distance-layer.hook.tsx
- libs/map/ui-map/src/lib/map.component.tsx
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-728
> [UKRIW-728] fix: fix not finishing drawing measure distance on double click

- libs/shared/utils/settings/src/lib/use-settings.hook.tsx
Increased AOI limit in ActionCreator workflow from 1 000 sq km to 10 000 sq km
> feat: increased aoi limit from 1000sq km to 10 000 sq km

- libs/map/data-access-map/src/lib/geometry/area-and-distance.ts
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-627
> [UKRIW-627] fix: fix area calculation for circle

- libs/shared/design-system/src/lib/tooltip/tooltip.tsx
- libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
- libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-645
> UKRIW-645 - bug fix for do not show again checkbox on onboarding tooltip

- libs/map/data-access-stac-catalog/src/lib/query-builder/collection.builder.ts
- libs/map/data-access-stac-catalog/src/lib/query-builder/query.builder.ts
- libs/map/data-access-stac-catalog/src/lib/stac-catalog.query.tsx
Tickets:
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-802
> [UKRIW-802] feat: change sort order to desc for stac collection

- libs/map/data-access-stac-catalog/src/lib/stac.model.ts
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-803
> UKRIW-803 - added NDWI to stac model

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
- libs/map/data-access-map/src/lib/mutation/workflow.error.tsx
- libs/map/data-access-stac-catalog/src/index.ts
- libs/map/data-access-stac-catalog/src/lib/no-results.error.ts
- libs/map/data-access-stac-catalog/src/lib/stac-catalog.query.tsx
- libs/map/data-access-stac-catalog/src/lib/workflow.error.ts
- libs/map/feature-action-creator-panel/src/lib/content/history/toggle-workflow-button.component.tsx
- libs/map/feature-search-mode-panel/src/lib/results-view.component.tsx
- libs/map/feature-search-mode-panel/src/lib/search-mode-panel.component.tsx
- libs/map/feature-search-mode-panel/src/lib/use-search-mode.hook.tsx
- libs/map/feature-timeline-analytics-dashboard/src/lib/graph-analytics.component.tsx
- libs/map/ui-results-view/src/lib/results-error.component.tsx
- libs/map/ui-results-view/src/lib/results-view.component.tsx
- libs/shared/design-system/src/index.ts
- libs/shared/design-system/src/lib/error/error.tsx
- libs/shared/design-system/src/lib/loader/results-view-loader/results-view-loader.tsx
- libs/shared/design-system/src/lib/merge.tailwind.ts
- package-lock.json
- package.json
- adjusted margin for errors in Result View
- different error messages for WF and Search
- hide back button in Error for WF errors in Result View
- change View button into hide button on error in WF history tab
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-735
> [UKRIW-735] feat: handle no items to process error

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
- libs/map/feature-action-creator-panel/src/lib/content/history/history.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/history/history.styles.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-537
> UKRIW-537 - No history message

- libs/map/ui-results-view/src/lib/results-list/result-item/result-item.component.tsx
- libs/map/ui-results-view/src/lib/results-list/results-list.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-806
> UKRIW-806 - fixed thumbnail to be clickable on Search Mode

- libs/map/ui-map/src/lib/layers/aoi-layer/use-aoi-layer.hook.tsx
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-813
> [UKRIW-813] feat: center map on AOI after preset load

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-372
> UKRIW-372 - Missing colon next to "Polarization" item in left menu

- libs/map/ui-map/src/lib/stac/projection.ts
- libs/map/ui-map/src/lib/stac/use-stac-layer-creation.tsx
- add support for EPSG:29902 projection
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-821
> [UKRIW-821] feat: add support for EPSG:29902 projection

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
- libs/map/data-access-map/src/lib/store/action-creator/action-creator.schema.ts
- libs/map/feature-action-creator-panel/src/lib/content/history/history.styles.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/data-set/use-active-dataset.hook.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/data-set/value-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/active-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/function-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/use-error-message.hook.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/value-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/workflow.component.tsx
- libs/map/ui-map/src/lib/stac/projection.ts
- libs/map/ui-map/src/lib/stac/use-stac-layer-creation.tsx
- libs/map/ui-search-view/src/lib/schema/data-sets/sentinel-2.schema.ts
- libs/shared/ui/time-slider/src/lib/time-slider.tsx
- libs/shared/utils/date/src/index.ts
- libs/shared/utils/date/src/lib/date.utils.ts
- package-lock.json
- package.json
- fix validation for Sentinel 2 ARD (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-819)
- fix button padding (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-512)
- add background in AC (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-741)
- add support for EPSG:29902 projection (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-821)
- timeslider fixes (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-576, https://ukri-spyrosoft.atlassian.net/browse/UKRIW-882)
> Release v0.15.0

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
- apps/eodh-fe/src/app/layout/help/help-modal.styles.tsx
- apps/eodh-fe/src/app/layout/help/translation-keys.tsx
- libs/map/feature-action-creator-panel/src/lib/content/help/translation-keys.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-827
> UKRIW-827 - Help content updates

- libs/map/ui-map/src/lib/layers/footprints-layer/use-footprint-layer.hook.tsx
- sort footprints to have the same order as in result list
- reverse array, on the map items are displayed in reversed order
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-815
> [UKRIW-815] feat: highlight first asset in the Result View

- libs/map/feature-action-creator-panel/src/lib/action-creator-panel.context.tsx
- libs/map/feature-action-creator-panel/src/lib/header/header.component.tsx
- automatically switch to Search Mode when user isn't logged out
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-840
> [UKRIW-840] fix: automatically switch to Search mode when user is logged out

- libs/map/ui-search-view/src/lib/checklist/checklist.component.stories.tsx
- libs/map/ui-search-view/src/lib/checklist/checklist.component.tsx
- libs/map/ui-search-view/src/lib/checklist/checklist.store.tsx
- libs/map/ui-search-view/src/lib/checklist/use-checklist.hook.tsx
- libs/map/ui-search-view/src/lib/schema/form.schema.ts
- libs/map/ui-search-view/src/lib/search-view.component.tsx
- fix bugs related to wrong AOI checkbox state in ckecklist
- change checklist mechanism for data sets to support dynamic data sets
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-440
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-586
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-595
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-603
Checklist generic requirements:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-62
> [UKRIW-440] [UKRIW-586] [UKRIW-595] [UKRIW-603] feat: fix checklist aoi. update checklist to support generic data sets

- libs/map/data-access-map/src/lib/form-builder/tree/schema/copernicus.schema.ts
- libs/map/data-access-map/src/lib/store/data-sets/data-sets.model.ts
- libs/map/data-access-map/src/lib/store/data-sets/data-sets.store.tsx
- libs/map/data-access-map/src/lib/store/toggle-mode.ts
- libs/map/data-access-map/src/lib/store/utils.ts
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/data-set/data-set-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/data-set/use-active-dataset.hook.tsx
- libs/map/feature-search-mode-panel/src/lib/use-search-mode.hook.tsx
- libs/map/ui-search-view/src/lib/search-view.component.tsx
- libs/map/ui-search-view/src/lib/use-form-update.component.tsx
- libs/shared/design-system/src/lib/slider/slider.tsx
Improve performance for Data Set tree. This partially solve issue - the issue still exists, but because of improved performance it is very edge case (user have to enable/disable AC 10-15 times)
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-822
> [UKRIW-822] feat: improve performance for Data Sets tree

- libs/shared/ui/time-slider/src/lib/time-slider.styles.ts
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-816
> UKRIW-816 - wrong padding bug fix

- libs/shared/ui/time-slider/src/lib/time-slider.styles.ts
- libs/shared/ui/time-slider/src/lib/time-slider.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-766
> UKRIW-766 - time slider disabled state

- libs/map/ui-map/src/lib/layers/comparison-mode-image-layer/comparison-tool-slider/comparison-tool-slider.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-820
> UKRIW-820 - slider fix

- libs/map/ui-search-view/src/lib/checklist/checklist.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-772
> UKRIW-772 - "Getting started" checklist visible in AC mode

- .github/workflows/deploy.yml
- apps/eodh-fe/public/config.js
- apps/eodh-fe/src/env/env.config.ts
- apps/storybook-host/.storybook/config/env.config.ts
- apps/storybook-host/public/assets/config.js
- docs/feature-flags.md
- libs/map/feature-action-creator-panel/src/lib/content/help/help.component.tsx
- libs/map/ui-results-view/src/lib/results-list/download-files.utils.ts
- libs/map/ui-results-view/src/lib/results-list/results-list.component.tsx
- libs/shared/utils/feature-flag/src/lib/feature-flag.context.tsx
- scripts/create-config-file.js
- fix downloading files in Safari. Safari was showing popup which was blocking opening files in new tab.
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-714
> [UKRIW-714] feat: fix downloading files in Safari

- libs/map/ui-search-view/src/lib/search-view.component.tsx
Trigger validation for Data Sets when switching between AC and Search mode
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-541
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-725
> [UKRIW-541] [UKRIW-725] feat: trigger validation for data sets when switching to AC mode

- libs/shared/utils/notification/src/lib/notification.ts
- package-lock.json
- package.json
fix for Safari bug that occur. after fix in https://ukri-spyrosoft.atlassian.net/browse/UKRIW-565
> UKRIW-565 - fixed Safari notification display time

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
- libs/map/feature-action-creator-panel/src/lib/content/help/translation-keys.tsx
- libs/shared/ui/help/src/lib/components/answer.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-859
> UKRIW-859 - help tab update

- libs/map/feature-action-creator-panel/src/lib/content/history/history-tile/history-tile.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-632
> UKRIW-632 - show full job id

- libs/shared/design-system/src/lib/tooltip/tooltip.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-607
> UKRIW-607 - tooltip close button position

- libs/map/ui-search-view/src/lib/checklist/checklist.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-866
> UKRIW-866 -  made "Getting started checklist" not visible on results View

- libs/map/data-access-map/src/lib/store/action-creator/workflow-import/import.workflow.ts
- libs/map/data-access-map/src/lib/store/date/date.model.ts
- libs/map/data-access-map/src/lib/store/date/date.store.tsx
- libs/map/data-access-map/src/lib/store/toggle-mode.ts
- libs/map/data-access-map/src/lib/store/utils.ts
- libs/map/ui-search-view/src/lib/search-view.component.tsx
Add different default values for Date Range for AC and Search. In AC date should be null by default.
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-505
> [UKRIW-505] feat: set null date as default in Search Panel for AC

- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/area-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/value-node.component.tsx
- libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/node.component.tsx
- libs/shared/utils/settings/src/lib/use-settings.hook.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-575
> UKRIW-575 - area node in ac bug fix

- libs/map/data-access-map/src/index.ts
- libs/map/data-access-map/src/lib/mutation/get-intersects.ts
- libs/map/data-access-map/src/lib/store/proj4.ts
- libs/map/data-access-stac-catalog/src/lib/query-builder/get-intersects.ts
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-695
> UKRIW-695 - AOI area bug fix for circle near to 10000km2

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-859
> UKRIW-859 - help content update

- libs/map/ui-map/src/lib/layers/measure-distance-layer/measure-distance-panel/measure-distance-panel.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-733
> UKRIW-733 - measurement tool placement fix

- libs/map/data-access-map/src/lib/store/action-creator/action-creator.store.tsx
- libs/map/data-access-map/src/lib/store/action-creator/workflow-import/import.workflow.ts
- libs/map/feature-action-creator-panel/src/lib/content/workflow/workflow.component.tsx
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-867
> UKRIW-867 - onboarding tooltip on import

- libs/map/data-access-stac-catalog/src/lib/stac-model/workflow.schema.ts
Remove opacity from color returned from TPZ API.
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-873
> [UKRIW-873] feat: remove opacity

- libs/map/data-access-stac-catalog/src/lib/stac-model/workflow.schema.ts
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-873
> [UKRIW-873] feat: add black color if color is not correct

- libs/map/data-access-map/src/lib/store/action-creator/action-creator.store.tsx
- libs/map/data-access-map/src/lib/store/action-creator/workflow-import/import.workflow.ts
- libs/map/data-access-map/src/lib/store/aoi/aoi.model.ts
- libs/map/data-access-map/src/lib/store/aoi/aoi.store.tsx
- libs/map/data-access-map/src/lib/store/utils.ts
- libs/map/feature-action-creator-panel/src/lib/content/history/use-load-history-results.hook.tsx
- remove AOI if WF results are loaded
- restore AOI on hide result button click
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-602
> [UKRIW-602] feat: remove AOI when WF results are displayed

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
https://ukri-spyrosoft.atlassian.net/browse/UKRIW-879
> UKRIW-879 - color code fixes

- libs/map/ui-map/src/lib/stac/color-map.color-map.ts
- display no data values as transparent for Water Quality in color map
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-825
> [UKRIW-825] feat: display no data values as transparent for Water Quality

- libs/map/data-access-map/src/index.ts
- libs/map/data-access-map/src/lib/query/function/function.query.tsx
- libs/map/data-access-map/src/lib/query/presets/presets.query.tsx
- libs/map/data-access-map/src/lib/query/protected-image.query.tsx
- libs/map/data-access-map/src/lib/query/stac-item.query.tsx
- libs/map/data-access-stac-catalog/src/lib/stac-catalog.query.tsx
- libs/map/ui-map/src/lib/stac/use-stac-layer-creation.tsx
- Add retry policy
- use QueryClient from TanStack as it supports complex retry policy (it has focus manager wich is handling if window is active)
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-868
> [UKRIW-868] feat: add retry policy

- libs/map/data-access-stac-catalog/src/lib/stac-model/asset.schema.ts
- libs/map/data-access-stac-catalog/src/lib/stac-model/workflow.schema.ts
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-885
> [UKRIW-885] feat: add nodata type for asset

- libs/map/data-access-stac-catalog/src/lib/query-builder/comercial/planet.query-builder.ts
- libs/map/ui-search-view/src/lib/dynamic-tree-form/elements/tree-category/use-slots.hook.tsx
- fix wrong setting wrong state in parent element in data sets
- limit collection for Planet to only supported ones
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-893
> [UKRIW-893] fix: fix wrong setting wrong state in parent element in data sets

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
- apps/eodh-fe/src/app/layout/help/translation-keys.tsx
- add help content for Sentinel 2 ARD
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-891
> [UKRIW-891] feat: update help content with Sentinel 2 ARD

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
- apps/eodh-fe/src/app/layout/help/translation-keys.tsx
- package-lock.json
- package.json
- [UKRIW-891] Add Sentinel 2 ARD to help content (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-891) [[UKRIW-891] feat: update help content with Sentinel 2 ARD](https://github.com/EO-DataHub/eodh-fe/pull/274)
> Release v1.2.1

- libs/map/data-access-map/src/lib/form-builder/tree/schema/planet.schema.ts
- disable Rapid Eye Data Set as it is not supported by CEDA.
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-896
> [UKRIW-896] feat: disable Rapid Eye Data Set

- libs/map/data-access-map/src/lib/form-builder/tree/schema/planet.schema.ts
- package-lock.json
- package.json
- [UKRIW-896] Disable RapidEye Planet Data Set (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-896) [[UKRIW-896] feat: disable Rapid Eye Data Set](https://github.com/EO-DataHub/eodh-fe/pull/277)
> Release v1.2.2

- libs/map/data-access-stac-catalog/src/lib/query-builder/public/fields/copernicus/sentinel-1.field.ts
- libs/map/data-access-stac-catalog/src/lib/query-builder/public/filter-params/copernicus/ceda/sentinel-1/ew-acquisition-mode.filter-params.ts
- libs/map/data-access-stac-catalog/src/lib/query-builder/public/filter-params/copernicus/ceda/sentinel-1/iw-acquisition-mode.filter-params.ts
- libs/map/data-access-stac-catalog/src/lib/stac-model/search.schema.ts
- update Sentinel 1 properties to adjust new CEDA Sentinel 1 schema
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-900
> [UKRIW-900] feat: update Sentinel 1 properties to adjust new CEDA Sentinel 1 schema

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
Remove content related to CORINE, Water Bodies and RapidEye in Help tab in AC.
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-902
> [UKRIW-902] feat: remove content related to CORINE, Water Bodies and RapidEye in Help tab in AC

- @types/i18next/resources.d.ts
- apps/eodh-fe/public/assets/i18n/en.json
- libs/map/feature-action-creator-panel/src/lib/content/help/translation-keys.tsx
- package-lock.json
- package.json
- [UKRIW-913] Update Help tab with Select Workspaces details (https://ukri-spyrosoft.atlassian.net/browse/UKRIW-913) [[UKRIW-913] feat: update help with workspaces](https://github.com/EO-DataHub/eodh-fe/pull/288)
> Release v1.4.1

- libs/map/ui-map/src/lib/layers/aoi-layer/edit-mode/edit-mode.context.tsx
- libs/map/ui-map/src/lib/layers/aoi-layer/edit-mode/use-edit.hook.tsx
- libs/map/ui-map/src/lib/layers/aoi-layer/edit-mode/use-rectangle-resize-edit.hook.tsx
- libs/map/ui-map/src/lib/layers/aoi-layer/use-aoi-layer.hook.tsx
- libs/map/ui-map/src/lib/map.component.tsx
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/EWEM-8
> [EWEM-8] Rescale rectangle

- libs/map/ui-map/src/lib/layers/aoi-layer/edit-mode/use-rectangle-resize-edit.hook.tsx
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/EWEM-14
> [EWEM-14] fix: fix resizing rectangle over edge

- libs/map/data-access-map/src/lib/store/aoi/aoi.model.ts
- libs/map/data-access-map/src/lib/store/aoi/aoi.store.tsx
- libs/map/ui-map/src/lib/layers/aoi-layer/edit-mode/edit-mode.context.tsx
- libs/map/ui-map/src/lib/layers/aoi-layer/edit-mode/use-edit.hook.tsx
- libs/map/ui-map/src/lib/layers/aoi-layer/edit-mode/use-rectangle-resize-edit.hook.tsx
- libs/map/ui-map/src/lib/layers/aoi-layer/edit-mode/use-simple-edit.hook.tsx
- libs/map/ui-map/src/lib/layers/aoi-layer/use-aoi-layer.hook.tsx
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/EWEM-15
> [EWEM-15] fix: fix resizing rectangle after importing Workflow

- libs/map/data-access-map/src/lib/store/action-creator/workflow-import/import-workflow.schema.ts
Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/EWEM-6
> [EWEM-6] feat: fix error with uploading old Workflows
